spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


    #  config:
#    activate:
#      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/learnova
    username: postgres
    password: Maktab
    driver-class-name: org.postgresql.Driver

jwt:
  secret: {secret Key}
  expiration-ms: 3600000

#  what is flyway
#  flyway:
#    community-db-support-enabled: true
#    logging:
#      level:
#        org:
#          flywaydb: DEBUG
